if(!window.MSL_SPEC){document.body.innerHTML='<main style="padding:24px;font-family:system-ui"><h1>스크립트 로드 오류</h1><p>js/spectrum.js 파일을 확인하세요.</p></main>';throw new Error('MSL_SPEC not loaded');}
const {CHANNELS,clamp,extractAll,meanSpectra,repeatScore,processAgainstBlank,mad,drawChart,csvRaw,csvMean}=window.MSL_SPEC;
const clone=o=>window.structuredClone?structuredClone(o):JSON.parse(JSON.stringify(o));
const $=id=>document.getElementById(id),ORDER=['blank','PP','PET','PS','PA','PC','unknown'],LABEL={blank:'Blank',PP:'PP Standard',PET:'PET Standard',PS:'PS Standard',PA:'PA Standard',PC:'PC Standard',unknown:'Unknown'};
const canvas=$('imageCanvas'),ctx=canvas.getContext('2d'),source=document.createElement('canvas'),sctx=source.getContext('2d',{willReadFrequently:true}),specCanvas=$('spectrumCanvas');
let session=null,activeKey=null,currentImage=null,currentDataUrl=null,currentSpectrum=null,drag=null,selectedChannel='gray',analysis=null,stream=null;
function uuid(){return (window.crypto&&crypto.randomUUID)?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2)}
function freshSession(name,mode,includeImages){const cards={};ORDER.forEach(k=>cards[k]={key:k,label:LABEL[k],standardId:['PP','PET','PS','PA','PC'].includes(k)?`${k}-STD-001`:null,captures:[],mean:null,sd:null,warning:false,acknowledged:false,done:false});return{id:uuid(),name,mode,includeImages,createdAt:new Date().toISOString(),roi:{x:0,y:0,w:0,h:0,locked:false,initialized:false},cards,activeIndex:0,result:null,thresholds:{repeatWarningMad:.08,unclassifiedMad:.20,separation:.15}}}
function saveState(){if(!session)return;const copy=clone(session);for(const c of Object.values(copy.cards))for(const cap of c.captures)delete cap.imageDataUrl;localStorage.setItem('msl_v2_session',JSON.stringify(copy))}
function loadState(){try{return JSON.parse(localStorage.getItem('msl_v2_session'))}catch{return null}}
function download(content,name,type='text/plain;charset=utf-8'){const blob=content instanceof Blob?content:new Blob([content],{type}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
function render(){const has=!!session;$('sessionStartPanel').classList.toggle('hidden',has);$('sessionTitle').textContent=has?session.name:'새 세션이 필요합니다';$('sessionMeta').textContent=has?`${session.mode==='photo'?'사진 3회':'3초 영상'} · ${new Date(session.createdAt).toLocaleString('ko-KR')}`:'사진 또는 3초 영상 모드를 선택하세요.';$('exportJsonBtn').disabled=!has;$('exportZipBtn').disabled=!has;renderSteps();renderCards();renderActive();if(session?.result)renderAnalysis()}
function renderSteps(){const done=session?ORDER.filter(k=>session.cards[k].done).length:0;$('progressText').textContent=`${done} / 7`;$('stepStrip').innerHTML=ORDER.map((k,i)=>`<div class="step ${session?.cards[k].done?'done':''} ${session&&i===session.activeIndex?'active':''}">${i+1}. ${k==='unknown'?'Unknown':k.toUpperCase()}</div>`).join('')}
function renderCards(){const wrap=$('measurementCards');if(!session){wrap.innerHTML='<p class="help">새 세션을 시작하면 측정 카드가 생성됩니다.</p>';return}wrap.innerHTML=ORDER.map((k,i)=>{const c=session.cards[k],cls=c.done?'done':c.warning?'warning':i===session.activeIndex?'active':'',disabled=i>session.activeIndex&&!c.done?'disabled':'';return`<button class="measurement-card ${cls}" data-key="${k}" ${disabled}><span class="top"><strong>${LABEL[k]}</strong><span>${c.done?'완료':c.captures.length+(session.mode==='photo'?'/3':'')}</span></span><small>${c.standardId|| (c.warning?'반복성 경고':c.done?'평균 생성 완료':'측정 대기')}</small></button>`}).join('');wrap.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>{activeKey=b.dataset.key;renderActive()})}
function activeCard(){return session?.cards[activeKey||ORDER[session.activeIndex]]}
function renderActive(){if(!session){$('activeCardTitle').textContent='측정 대기';$('activeCardHint').textContent='새 세션을 시작하세요.';return}if(!activeKey)activeKey=ORDER[session.activeIndex];const c=activeCard(),isStd=!!c.standardId;$('activeCardTitle').textContent=c.label;$('activeCardHint').textContent=session.mode==='photo'?'같은 시료를 고정한 채 연속 3회 측정하세요.':'ROI를 맞춘 뒤 3초간 유효 프레임을 수집합니다.';$('activeStatus').textContent=c.done?'완료':c.warning?'경고':c.captures.length?'측정 중':'대기';$('activeStatus').className='status '+(c.done?'done':c.warning?'warn':'active');$('standardIdRow').classList.toggle('hidden',!isStd);if(isStd){$('standardIdInput').value=c.standardId;$('standardIdInput').onchange=e=>{c.standardId=e.target.value.trim()||`${c.key}-STD-001`;saveState();renderCards()}}$('photoControls').classList.toggle('hidden',session.mode!=='photo');$('videoControls').classList.toggle('hidden',session.mode!=='video');$('photoRepeatLabel').textContent=`측정 ${Math.min(c.captures.length+1,3)} / 3`;$('saveCaptureBtn').style.display=session.mode==='photo'?'':'none';$('saveCaptureBtn').disabled=!currentSpectrum||c.done||c.captures.length>=3;$('completeCardBtn').disabled=c.done||(session.mode==='photo'?c.captures.length!==3:c.captures.length!==1);$('retakeCardBtn').disabled=!c.captures.length&&!c.done;renderCaptureList();syncRoiInputs();renderWarning(c)}
function renderCaptureList(){const c=activeCard();$('captureList').innerHTML=c.captures.map((x,i)=>`<div class="capture-item"><span>${session.mode==='photo'?`측정 ${i+1}`:`유효 프레임 ${x.validFrames||0}개`} · ${x.spectrum.gray.length} points</span><button class="btn" data-dl="${i}">Raw CSV</button></div>`).join('')+(c.mean?`<div class="capture-item"><strong>평균 Raw</strong><button class="btn" id="meanCsvBtn">평균 CSV</button></div>`:'');$('captureList').querySelectorAll('[data-dl]').forEach(b=>b.onclick=()=>downloadCapture(+b.dataset.dl));$('meanCsvBtn')?.addEventListener('click',downloadMean)}
function renderWarning(c){const el=$('repeatWarning');el.classList.toggle('hidden',!c.warning);if(c.warning)el.innerHTML=`<strong>반복성 경고</strong><br>3회 측정의 정규화 Gray 평균 MAD가 ${c.repeatMad.toFixed(4)}입니다. 원자료는 삭제하지 않았습니다.`}
function syncRoiInputs(){if(!session)return;const r=session.roi;for(const [id,k] of [['roiX','x'],['roiY','y'],['roiW','w'],['roiH','h']]){$(id).value=Math.round(r[k]||0);$(id).disabled=!currentImage||(r.locked&&(k==='w'||k==='h'))}$('roiSummary').textContent=r.initialized?`${Math.round(r.w)} × ${Math.round(r.h)}${r.locked?' 🔒':''}`:'미설정'}
function initRoi(w,h){const r=session.roi;if(!r.initialized){r.w=Math.round(w*.22);r.h=Math.round(h*.13);r.x=Math.round((w-r.w)/2);r.y=Math.round((h-r.h)/2);r.initialized=true}r.w=clamp(r.w,8,w);r.h=clamp(r.h,8,h);r.x=clamp(r.x,0,w-r.w);r.y=clamp(r.y,0,h-r.h)}
function loadFile(file){if(!file||!session)return;const fr=new FileReader();fr.onload=()=>{const im=new Image();im.onload=()=>{currentImage=im;currentDataUrl=fr.result;source.width=im.naturalWidth;source.height=im.naturalHeight;sctx.drawImage(im,0,0);canvas.width=im.naturalWidth;canvas.height=im.naturalHeight;initRoi(canvas.width,canvas.height);$('viewerWrap').classList.remove('empty');$('viewerEmpty').style.display='none';updatePreview()};im.src=fr.result};fr.readAsDataURL(file)}
function updatePreview(){if(!currentImage&&!stream)return;const r=session.roi;if(currentImage){ctx.drawImage(currentImage,0,0,canvas.width,canvas.height);currentSpectrum=extractAll(sctx,r)}drawRoi();drawCurrentSpectrum();syncRoiInputs();$('saveCaptureBtn').disabled=!currentSpectrum||activeCard().done||activeCard().captures.length>=3}
function drawRoi(){const r=session.roi;ctx.save();ctx.fillStyle='rgba(250,204,21,.12)';ctx.strokeStyle='#facc15';ctx.lineWidth=Math.max(3,canvas.width/500);ctx.fillRect(r.x,r.y,r.w,r.h);ctx.strokeRect(r.x,r.y,r.w,r.h);ctx.fillStyle='#facc15';const hs=Math.max(18,canvas.width/80);ctx.fillRect(r.x+r.w-hs,r.y+r.h-hs,hs,hs);ctx.restore()}
function drawCurrentSpectrum(){if(!currentSpectrum)return;const mode=$('previewChannel').value,series=mode==='overlay'?CHANNELS.filter(k=>k!=='gray').map(k=>({key:k,label:k[0].toUpperCase(),values:currentSpectrum[k]})):[{key:mode,label:mode,values:currentSpectrum[mode]}];drawChart(specCanvas,series,{yMin:0,yMax:255})}
function pointerPos(e){const rect=canvas.getBoundingClientRect();return{x:(e.clientX-rect.left)*canvas.width/rect.width,y:(e.clientY-rect.top)*canvas.height/rect.height}}
canvas.onpointerdown=e=>{if(!currentImage)return;const p=pointerPos(e),r=session.roi,hs=Math.max(28,canvas.width/60);if(p.x>=r.x+r.w-hs&&p.y>=r.y+r.h-hs&&!r.locked)drag={mode:'resize',p,r:{...r}};else if(p.x>=r.x&&p.x<=r.x+r.w&&p.y>=r.y&&p.y<=r.y+r.h)drag={mode:'move',p,r:{...r}};if(drag)canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;const p=pointerPos(e),r=session.roi,dx=p.x-drag.p.x,dy=p.y-drag.p.y;if(drag.mode==='move'){r.x=clamp(drag.r.x+dx,0,canvas.width-r.w);r.y=clamp(drag.r.y+dy,0,canvas.height-r.h)}else{r.w=clamp(drag.r.w+dx,8,canvas.width-r.x);r.h=clamp(drag.r.h+dy,8,canvas.height-r.y)}updatePreview()};canvas.onpointerup=()=>{drag=null;saveState()};
for(const [id,k] of [['roiX','x'],['roiY','y'],['roiW','w'],['roiH','h']])$(id).onchange=e=>{if(!session||!currentImage)return;session.roi[k]=Number(e.target.value);initRoi(canvas.width,canvas.height);updatePreview();saveState()};
function savePhotoCapture(){const c=activeCard();if(!currentSpectrum||c.captures.length>=3)return;c.captures.push({id:uuid(),createdAt:new Date().toISOString(),roi:{...session.roi},spectrum:clone(currentSpectrum),imageDataUrl:session.includeImages?currentDataUrl:null});if(c.key==='blank'&&c.captures.length===1)session.roi.locked=true;currentImage=null;currentSpectrum=null;currentDataUrl=null;ctx.clearRect(0,0,canvas.width,canvas.height);$('viewerEmpty').style.display='grid';$('viewerWrap').classList.add('empty');drawChart(specCanvas,[]);saveState();render();activeKey=c.key}
function completeCard(){const c=activeCard(),spectra=c.captures.map(x=>x.spectrum),avg=meanSpectra(spectra);if(!avg)return;c.mean=avg.mean;c.sd=avg.sd;c.repeatMad=repeatScore(spectra);c.warning=session.mode==='photo'&&c.repeatMad>session.thresholds.repeatWarningMad;c.done=true;session.activeIndex=Math.max(session.activeIndex,ORDER.indexOf(c.key)+1);if(session.activeIndex>=ORDER.length){session.activeIndex=ORDER.length-1;runAnalysis()}else activeKey=ORDER[session.activeIndex];saveState();render()}
function retake(){const c=activeCard();if(!confirm(`${c.label}의 모든 측정값을 삭제하고 다시 측정할까요?`))return;c.captures=[];c.mean=null;c.sd=null;c.warning=false;c.done=false;session.result=null;session.activeIndex=ORDER.indexOf(c.key);activeKey=c.key;analysis=null;$('analysisSection').classList.add('hidden');saveState();render()}
async function startCamera(){if(stream)return;if(location.protocol==='file:'){alert('카메라 직접 실행은 브라우저 보안 정책상 file://에서 제한될 수 있습니다. 사진 불러오기는 로컬에서 가능하며, 카메라는 GitHub Pages(HTTPS)에서 테스트하세요.');}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});const v=$('liveVideo');v.srcObject=stream;v.classList.remove('hidden');await v.play();$('viewerEmpty').style.display='none';$('viewerWrap').classList.remove('empty');$('startCameraBtn').textContent='카메라 켜짐';$('captureVideoBtn').disabled=false;requestAnimationFrame(videoLoop)}catch(e){alert('카메라를 열 수 없습니다: '+e.message)}}
function videoLoop(){if(!stream)return;const v=$('liveVideo');if(v.videoWidth){canvas.width=v.videoWidth;canvas.height=v.videoHeight;source.width=v.videoWidth;source.height=v.videoHeight;initRoi(canvas.width,canvas.height);sctx.drawImage(v,0,0);ctx.drawImage(v,0,0);drawRoi();currentSpectrum=extractAll(sctx,session.roi);drawCurrentSpectrum();syncRoiInputs()}requestAnimationFrame(videoLoop)}
async function captureVideo(){const c=activeCard();if(c.done)return;$('captureVideoBtn').disabled=true;const frames=[],start=performance.now();while(performance.now()-start<3000){const left=Math.ceil((3000-(performance.now()-start))/1000);$('videoTimer').textContent=`${Math.max(0,left)}초`;sctx.drawImage($('liveVideo'),0,0,source.width,source.height);const sp=extractAll(sctx,session.roi),g=sp.gray,mean=g.reduce((a,b)=>a+b,0)/g.length,sat=g.filter(v=>v>=250).length/g.length;if(mean>5&&mean<250&&sat<.05)frames.push(sp);await new Promise(r=>setTimeout(r,120))}$('videoTimer').textContent='완료';if(frames.length<3){alert('유효 프레임이 부족합니다. 조명과 ROI를 확인하세요.');$('captureVideoBtn').disabled=false;return}const avg=meanSpectra(frames);c.captures=[{id:uuid(),createdAt:new Date().toISOString(),roi:{...session.roi},spectrum:avg.mean,frameSd:avg.sd,validFrames:frames.length,validFrameSpectra:frames}];c.mean=avg.mean;c.sd=avg.sd;c.warning=repeatScore(frames)>.08;c.repeatMad=repeatScore(frames);$('completeCardBtn').disabled=false;saveState();renderActive()}
function runAnalysis(){if(!ORDER.every(k=>session.cards[k].done))return;const blank=session.cards.blank.mean,processed={};for(const k of ORDER.filter(k=>k!=='blank'))processed[k]=processAgainstBlank(session.cards[k].mean,blank);const rankings={},statuses={};for(const ch of CHANNELS){const u=processed.unknown[ch],rows=['PP','PET','PS','PA','PC'].map(mat=>({material:mat,mad:mad(u.normalized,processed[mat][ch].normalized,u.mask)})).sort((a,b)=>a.mad-b.mad),best=rows[0],second=rows[1],sep=(second.mad-best.mad)/(second.mad||1);let status=best.mad>session.thresholds.unclassifiedMad?'미분류':sep<session.thresholds.separation?'불확실':'1순위 후보';rankings[ch]=rows;statuses[ch]={status,best:best.material,bestMad:best.mad,separation:sep}}const leaders=CHANNELS.map(ch=>statuses[ch].best),mismatch=new Set(leaders).size>1;analysis={processed,rankings,statuses,mismatch,createdAt:new Date().toISOString(),activeChannel:'gray'};session.result={rankings,statuses,mismatch,createdAt:analysis.createdAt};saveState();renderAnalysis()}
function renderAnalysis(){if(!analysis&&session.result)runAnalysis();if(!analysis)return;$('analysisSection').classList.remove('hidden');const g=analysis.statuses.gray;$('resultSummary').innerHTML=`<div class="result-big">${g.status}: ${g.best}</div><p>Gray MAD ${g.bestMad.toFixed(6)} · 분리도 ${(g.separation*100).toFixed(1)}%</p>${analysis.mismatch?'<div class="warning"><strong>채널 불일치</strong><br>'+CHANNELS.map(c=>`${c}: ${analysis.statuses[c].best}`).join(' · ')+'</div>':'<p>Gray·R·G·B 채널의 1순위가 일치합니다.</p>'}`;$('channelTabs').innerHTML=CHANNELS.map(ch=>`<button class="tab ${ch===analysis.activeChannel?'active':''}" data-ch="${ch}">${ch.toUpperCase()}</button>`).join('');$('channelTabs').querySelectorAll('[data-ch]').forEach(b=>b.onclick=()=>{analysis.activeChannel=b.dataset.ch;renderAnalysisCharts();renderAnalysis()});renderAnalysisCharts()}
function renderAnalysisCharts(){const ch=analysis.activeChannel,series=['PP','PET','PS','PA','PC'].map(k=>({key:k,label:k,values:analysis.processed[k][ch].attenuation}));series.unshift({key:'unknown',label:'Unknown',values:analysis.processed.unknown[ch].attenuation,width:3});drawChart($('analysisSpectrumCanvas'),series,{yLabel:'1 - I/I₀'});const best=analysis.statuses[ch].best,u=analysis.processed.unknown[ch].normalized,s=analysis.processed[best][ch].normalized,d=u.map((v,i)=>Math.abs(v-s[i]));drawChart($('differenceCanvas'),[{key:'unknown',label:`|Unknown-${best}|`,values:d}],{yMin:0,yMax:1,yLabel:'Absolute difference'});$('rankingTable').innerHTML=`<table class="rank-table"><thead><tr><th>순위</th><th>재질</th><th>MAD</th></tr></thead><tbody>${analysis.rankings[ch].map((r,i)=>`<tr><td>${i+1}</td><td>${r.material}</td><td>${r.mad.toFixed(6)}</td></tr>`).join('')}</tbody></table>`}
function downloadCapture(i){const c=activeCard(),cap=c.captures[i];download(csvRaw(cap.spectrum,{session:session.name,type:c.key,standard_id:c.standardId||'',capture:i+1,roi:`${cap.roi.x} ${cap.roi.y} ${cap.roi.w} ${cap.roi.h}`}),`${c.standardId||c.key}_raw_${String(i+1).padStart(2,'0')}.csv`,'text/csv')}
function downloadMean(){const c=activeCard();download(csvMean(c.mean,c.sd,{session:session.name,type:c.key,standard_id:c.standardId||'',repeat_warning:c.warning}),`${c.standardId||c.key}_raw_mean.csv`,'text/csv')}
function processedCsv(){const rows=['sample,channel,pixel,raw,blank,transmittance,relative_attenuation,normalized,valid'];for(const [sample,p] of Object.entries(analysis.processed))for(const ch of CHANNELS)for(let i=0;i<p[ch].raw.length;i++)rows.push([sample,ch,i,p[ch].raw[i],p[ch].blank[i],p[ch].transmittance[i],p[ch].attenuation[i],p[ch].normalized[i],p[ch].mask[i]].map((v,j)=>typeof v==='number'&&j>2?Number(v).toFixed(6):v).join(','));return rows.join('\n')}
function madCsv(){const rows=['channel,rank,material,mad,status,separation'];for(const ch of CHANNELS)analysis.rankings[ch].forEach((r,i)=>rows.push(`${ch},${i+1},${r.material},${r.mad.toFixed(6)},${i===0?analysis.statuses[ch].status:''},${i===0?analysis.statuses[ch].separation.toFixed(6):''}`));return rows.join('\n')}
async function exportZip(){if(!session)return;const zip=new JSZip(),root=zip.folder(`MSL_${session.id.slice(0,8)}`);root.file('session.json',JSON.stringify(session,(k,v)=>k==='imageDataUrl'?undefined:v,2));const raw=root.folder('raw');for(const k of ORDER){const c=session.cards[k],dir=raw.folder(k);c.captures.forEach((cap,i)=>{dir.file(`${c.standardId||k}_raw_${String(i+1).padStart(2,'0')}.csv`,csvRaw(cap.spectrum,{session:session.name,type:k,standard_id:c.standardId||''}));if(session.includeImages&&cap.imageDataUrl){const base=cap.imageDataUrl.split(',')[1];dir.file(`${c.standardId||k}_image_${String(i+1).padStart(2,'0')}.jpg`,base,{base64:true})}});if(c.mean)dir.file(`${c.standardId||k}_raw_mean.csv`,csvMean(c.mean,c.sd,{repeat_warning:c.warning}))}if(analysis){root.folder('processed').file('all_processed.csv',processedCsv());root.folder('results').file('mad_results.csv',madCsv())}const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE'});download(blob,`MSL_${new Date().toISOString().replaceAll(':','-')}.zip`)}
function createFixedModeSession(mode){if(session&&!confirm('현재 세션을 종료하고 새 세션을 시작할까요?'))return;session=freshSession($('sessionNameInput').value.trim()||'분광 분석 세션',mode,$('includeImagesCheck').checked);activeKey='blank';analysis=null;localStorage.removeItem('msl_v2_session');saveState();render();window.scrollTo({top:0,behavior:'smooth'})}
$('newSessionBtn').onclick=()=>{if(session&&!confirm('현재 세션을 종료하고 새 세션 선택 화면으로 돌아갈까요?'))return;session=null;activeKey=null;analysis=null;localStorage.removeItem('msl_v2_session');$('analysisSection').classList.add('hidden');render();$('sessionStartPanel').scrollIntoView({behavior:'smooth',block:'start'})};$('startPhotoSessionBtn').onclick=()=>createFixedModeSession('photo');$('startVideoSessionBtn').onclick=()=>createFixedModeSession('video');$('cameraPhotoInput').onchange=e=>{loadFile(e.target.files[0]);e.target.value=''};$('galleryInput').onchange=e=>{loadFile(e.target.files[0]);e.target.value=''};$('previewChannel').onchange=drawCurrentSpectrum;$('saveCaptureBtn').onclick=savePhotoCapture;$('completeCardBtn').onclick=completeCard;$('retakeCardBtn').onclick=retake;$('startCameraBtn').onclick=startCamera;$('captureVideoBtn').onclick=captureVideo;$('runAnalysisBtn').onclick=runAnalysis;$('exportJsonBtn').onclick=()=>download(JSON.stringify(session,(k,v)=>k==='imageDataUrl'?undefined:v,2),`MSL_${session.id}.json`,'application/json');$('exportZipBtn').onclick=exportZip;$('downloadProcessedBtn').onclick=()=>download(processedCsv(),'processed_data.csv','text/csv');$('downloadMadBtn').onclick=()=>download(madCsv(),'mad_results.csv','text/csv');$('downloadGraphBtn').onclick=()=>$('analysisSpectrumCanvas').toBlob(b=>download(b,'attenuation_graph.png','image/png'));
const restored=loadState();if(restored){session=restored;activeKey=ORDER[Math.min(session.activeIndex,6)];if(session.result&&ORDER.every(k=>session.cards[k].done))runAnalysis()}render();drawChart(specCanvas,[]);

console.info('Mobile Spectrum Lab v2.0.3-fixed-mode-buttons loaded');
